import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import Track from "./components/Track";
import { forwardRef, useRef, useImperativeHandle, useState } from "react";

import WaveSurferNext from "./components/Track/WaveSurferNext.jsx";

import { Provider } from "react-redux";
import store from "../store";

const url1 =
  "https://www.mfiles.co.uk/mp3-downloads/brahms-st-anthony-chorale-theme-two-pianos.mp3";
const url2 = "https://www.mfiles.co.uk/mp3-downloads/pachelbel-canon-in-d.mp3";
// const url3 = "public/audio/20220927_快樂丸.mp3";

export default function Home() {
  const playRef = useRef<HTMLAudioElement>(null);
  const [playing, setPlaying] = useState(false);

  return (
    <Provider store={store}>
      <div className={styles.container}>
        <Head>
          <title>Online DAW</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <WaveSurferNext setPlaying={setPlaying} ref={playRef} url={url1} />
        <WaveSurferNext setPlaying={setPlaying} ref={playRef} url={url2} />
        {/* <button onClick={() => playRef.current.handlePlayPause()}>
          {!playing ? "Play" : "Pause"}
        </button> */}
      </div>
    </Provider>
  );
}
