import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
// import { forwardRef, useRef, useImperativeHandle, useState } from "react";
import styled from "styled-components";

const Container = styled.div`
  max-width: 1280px;
  max-height: 80%;
  padding: 100px 0;
  margin: 0px auto;
  display: flex;
  flex-direction: column;
`;

const Title = styled.h1`
  font-size: 150px;
  font-weight: 700;
  color: #f6ddcd;
  /* margin-top: 100px; */
`;

const SubTitle = styled.h1`
  font-size: 100px;
  font-weight: 700;
  color: #f6ddcd;
`;
const Description = styled.p`
  font-size: 18px;
  color: #f6ddcd;
  margin-top: 30px;
`;
const Links = styled.div`
  display: flex;
  /* margin-top: 100px; */
  bottom: 0px;
  column-gap: 50px;
`;
const LinkText = styled.p`
  font-size: 36px;
  color: #f6ddcd;
  font-weight: 700;
  &:hover {
    text-decoration: underline;
    text-underline-offset: 5px;
  }
`;

export default function Home() {
  return (
    <>
      <Container>
        <Head>
          <title>Online DAW</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Title>online DAW</Title>
        <SubTitle>100％ FREE</SubTitle>
        <Description>
          Our award-winning music creation features empower you with everything
          you need for your next big hit. Create, collaborate and sync across
          platforms, all with unlimited cloud storage.
        </Description>
        <Links>
          <Link href={`/dashboard`}>
            <LinkText>dashboard</LinkText>
          </Link>
          <Link href={`/login`}>
            <LinkText>login</LinkText>
          </Link>
          <Link href={`/signup`}>
            <LinkText>signup</LinkText>
          </Link>
        </Links>
      </Container>
    </>
  );
}
