import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import AllPanels from "../../src/components/AllPanels";
import { useAuth } from "../../src/context/AuthContext";
import {
  tracksDataState,
  projectDataState,
  playingNoteState,
  selectedTrackIdState,
  selectedTrackIndexState,
  barWidthState,
  progressState,
  isPlayingState,
  isMetronomeState,
  isLoadingState,
  playerStatusState,
  TrackData,
  NoteData,
  AudioData,
  ClipData,
} from "../../src/context/atoms";
import { useRecoilState, useRecoilValue, useSetRecoilState } from "recoil";

const ProjectDetail = () => {
  const router = useRouter();
  const { projectId } = router.query;
  const { user, logout } = useAuth();
  const projectData = useRecoilValue(projectDataState);

  useEffect(() => {
    if (!user) {
      router.push("/login");
    }
  }, [router, user]);

  return (
    <>
      <Head>
        <title>{`${projectData?.name} - ${user?.displayName} | Online DAW`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-pattern.svg" />
      </Head>
      <AllPanels projectId={projectId || "1234"} />
    </>
  );
};

export default ProjectDetail;
