import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import AllPanels from "../../src/components/AllPanels";
import { useAuth } from "../../src/context/AuthContext";
import {
  tracksDataState,
  // projectDataState,
  playingNoteState,
  selectedTrackIdState,
  selectedTrackIndexState,
  barWidthState,
  progressState,
  isPlayingState,
  isMetronomeState,
  isLoadingState,
  playerStatusState,
  TrackData,
  NoteData,
  AudioData,
  ClipData,
  ProjectData,
} from "../../src/store/atoms";
import {
  useRecoilState,
  useRecoilValue,
  useSetRecoilState,
  atom,
} from "recoil";

const projectDataState = atom({
  key: "projectDataState",
  default: {
    createdTime: null,
    id: "",
    name: "",
    ownerId: "",
    ownerName: "",
    tempo: 60,
  } as ProjectData,
});

const ProjectDetail = () => {
  const router = useRouter();
  const { projectId } = router.query;
  const { user } = useAuth();
  const projectData = useRecoilValue(projectDataState);

  useEffect(() => {
    if (!user || !projectId) {
      router.push("/login");
    }
  }, [router, user, projectId]);

  return (
    <>
      <Head>
        <title>{`${projectData?.name} - ${user?.displayName} | Online DAW`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-pattern.svg" />
      </Head>
      {typeof projectId === "string" && <AllPanels projectId={projectId} />}
    </>
  );
};

export default ProjectDetail;
